name: multimodal_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch-cuda=12.4
  - pytorch>=2.6.0
  - torchvision>=0.21.0
  - torchaudio>=2.6.0
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pillow
  - pip
  - pip:
    - pyyaml
    - transformers
    - datasets
    - wandb
    - fastapi
    - uvicorn
    - python-multipart
    - opencv-python
    - mtcnn
    - pyenchant
    - nltk
    - emoji
    - gdown
    - kaggle
    - librosa
    - soundfile
